spring:
  application:
    name: social
    #自定义链接（别名）
  instance:
    hostname: Social
    # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: toor
    type: com.alibaba.druid.pool.DruidDataSource
#    type: org.apache.tomcat-jdbc.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        #        login-password: ENC(PYVnAYh+j5C3jkMV1d+myj6JzDaUk7pcfTWUaYsvQdEVkuvIVf7Y0mOU9XkffxT8)
        login-password: toor
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 显示慢sql 默认当超过3秒显示
          log-slow-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/,http://localhost:8762/eureka/

#日志输出级别
logging:
  level:
    root: info
    com.jluzh.user.*: trace

#负载均衡策略
CLIENT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
